apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: 192.168.1.100
      user: uhstray
      port: 22
      keyPath: ~/OneDrive/Documents/GitHub/awx-operations/deployments/ubuntu/22.04/config/hoagsobject
    role: controller+worker
  - ssh:
      address: 192.168.1.102
      user: uhstray
      port: 22
      keyPath: ~/OneDrive/Documents/GitHub/awx-operations/deployments/ubuntu/22.04/config/mercier77
    role: controller+worker
  - ssh:
      address: 192.168.1.101
      user: uhstray
      port: 22
      keyPath: ~/OneDrive/Documents/GitHub/awx-operations/deployments/ubuntu/22.04/config/crabnebula
    role: worker
  - ssh:
      address: 192.168.1.103
      user: uhstray
      port: 22
      keyPath: ~/OneDrive/Documents/GitHub/awx-operations/deployments/ubuntu/22.04/config/ngc7764a
    role: worker
  k0s:
    version: null
    versionChannel: stable
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          kubeProxy:
            disabled: false
            mode: iptables
          kuberouter:
            autoMTU: true
            mtu: 0
            metricsPort: 8080
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false